/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tugassemester2;
import javax.swing.*;
import java.awt.event.*;
/**
 *
 * @author TeranixBQ
 */
public class FormMhs extends javax.swing.JFrame {
    ClassMhs cls = new ClassMhs();
    String nama,nim2;
    /**
     * Creates new form FormMhs
     */
    public FormMhs(String nama, String nim2) {
    
        initComponents();
        this.nama = nama;
        this.nim2 = nim2;
        tnama1.setText(this.nama);
        tnim1.setText(this.nim2);
        
        nonaktif();
    }

    void aktif(){
        tuts.setEnabled(true);
        tuas.setEnabled(true);
        ttugas.setEnabled(true);
        thadir.setEnabled(true);
        takhir.setEnabled(true);
    }
    
    void hapus(){
        tuts.setText("");
        tuas.setText("");
        ttugas.setText("");
        thadir.setText("");
        takhir.setText("");
        tgrade.setText("");
    }
    
    void nonaktif(){
        tnim1.setEnabled(false);
        takhir.setEnabled(false);
        tgrade.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tuts = new javax.swing.JTextField();
        tuas = new javax.swing.JTextField();
        ttugas = new javax.swing.JTextField();
        thadir = new javax.swing.JTextField();
        bhapus = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        bhitung = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tnama1 = new javax.swing.JTextField();
        tnim1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        takhir = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tgrade = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bkeluar = new javax.swing.JButton();
        jkembali = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel1.setText("UTS                :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel2.setText("UAS                :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel3.setText("TUGAS           :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel4.setText("KEHADIRAN  :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        tuts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutsActionPerformed(evt);
            }
        });
        tuts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tutsKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tutsKeyTyped(evt);
            }
        });
        jPanel1.add(tuts, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 39, -1));

        tuas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tuasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tuasKeyTyped(evt);
            }
        });
        jPanel1.add(tuas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 39, -1));

        ttugas.setToolTipText("");
        ttugas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ttugasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ttugasKeyTyped(evt);
            }
        });
        jPanel1.add(ttugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 39, -1));

        thadir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                thadirKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                thadirKeyTyped(evt);
            }
        });
        jPanel1.add(thadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 39, -1));

        bhapus.setBackground(new java.awt.Color(153, 153, 255));
        bhapus.setText("Hapus");
        bhapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });
        jPanel1.add(bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 100, 30));

        jLabel6.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel6.setText("Data Nilai");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        bhitung.setBackground(new java.awt.Color(153, 153, 255));
        bhitung.setText("Hitung");
        bhitung.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhitungActionPerformed(evt);
            }
        });
        jPanel1.add(bhitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 90, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/vertical-line-removebg-preview (2).png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 50, 140));

        jLabel8.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel8.setText("Hasil");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel5.setText("Nama         :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 103, 70, -1));

        jLabel9.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel9.setText("Nim            :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 134, 70, -1));

        tnama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnama1ActionPerformed(evt);
            }
        });
        jPanel1.add(tnama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 100, 145, -1));

        tnim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnim1ActionPerformed(evt);
            }
        });
        jPanel1.add(tnim1, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 131, 145, -1));

        jLabel10.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel10.setText("Nilai Akhir :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 165, -1, -1));
        jPanel1.add(takhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 162, 57, -1));

        jLabel11.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel11.setText("Grade         :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 196, -1, -1));

        tgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgradeActionPerformed(evt);
            }
        });
        jPanel1.add(tgrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 193, 57, -1));

        jLabel12.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel12.setText("UNIVERSITAS");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, -1, -1));

        jLabel13.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 102, 0));
        jLabel13.setText("MANDIRI");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 60, 17));

        jLabel14.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 153));
        jLabel14.setText("NUSA");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 40, -1));

        bkeluar.setBackground(new java.awt.Color(255, 102, 102));
        bkeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/power_on_off_icon_153694 (2).png"))); // NOI18N
        bkeluar.setText("Keluar");
        bkeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });
        jPanel1.add(bkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 100, 30));

        jkembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/back_arrow_14447 (2).png"))); // NOI18N
        jkembali.setBorderPainted(false);
        jkembali.setContentAreaFilled(false);
        jkembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkembaliActionPerformed(evt);
            }
        });
        jPanel1.add(jkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/rm222-mind-22 (2).jpg"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(572, 406));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
    hapus();
    }//GEN-LAST:event_bhapusActionPerformed

    private void bhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhitungActionPerformed
     
  
      if(tuts.getText().equals("")||tuas.getText().equals("")||ttugas.getText().equals("")||thadir.getText().equals("")){
          JOptionPane.showMessageDialog(null, "Data Nilai Harus Di isi semua","Error",JOptionPane.ERROR_MESSAGE);
            return;
      }
      else{
            cls.setnuts(Double.parseDouble(tuts.getText()));
            cls.setuas(Double.parseDouble(tuas.getText()));
            cls.settugas(Double.parseDouble(ttugas.getText()));
            cls.setnkehadiran(Double.parseDouble(thadir.getText()));
            takhir.setText(Double.toString(cls.getNilaiAkhir2()));
            cls.getNilaiGrade();
            tgrade.setText(cls.getGrd());
//            cls.getNilaiGrade();
//            tgrade.setText(nama);
//            double total = cls.ttl;
//            if (total >= 80 && total <=100) {
//            grade = "A";
//            }
//            else if (total >= 68 && total <= 79){
//                grade = "B";
//             }
//            else if (total >= 56 && total <= 67){
//                grade = "C";
//            }
//             else if (total >= 45 && total <= 55){
//                grade = "D";
//            }
//            else {
//                grade = "E";
//            }
//            
//            tgrade.setText(grade);

      
      }            
    }//GEN-LAST:event_bhitungActionPerformed

    private void tnama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnama1ActionPerformed

    }//GEN-LAST:event_tnama1ActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        int tutup;
        tutup = JOptionPane.showConfirmDialog(null, " Tutup program?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if (tutup == JOptionPane.YES_OPTION)
        {dispose();}
        else
        {return;}
    }//GEN-LAST:event_bkeluarActionPerformed

    private void jkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkembaliActionPerformed
        MasukMhs masuk = new MasukMhs();
        masuk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jkembaliActionPerformed

    private void tnim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnim1ActionPerformed
  
    }//GEN-LAST:event_tnim1ActionPerformed

    private void tutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutsActionPerformed

    }//GEN-LAST:event_tutsActionPerformed

    private void tutsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tutsKeyTyped
    cls.angka(evt);
    }//GEN-LAST:event_tutsKeyTyped

    private void tuasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tuasKeyTyped
    cls.angka(evt);
    }//GEN-LAST:event_tuasKeyTyped

    private void ttugasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ttugasKeyTyped
    cls.angka(evt);
    }//GEN-LAST:event_ttugasKeyTyped

    private void thadirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_thadirKeyTyped
    cls.angka(evt);
    }//GEN-LAST:event_thadirKeyTyped

    private void tgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgradeActionPerformed

    }//GEN-LAST:event_tgradeActionPerformed

    private void tutsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tutsKeyReleased
    int input = Integer.valueOf(tuts.getText().trim());
    if ((input < 0)){
        JOptionPane.showMessageDialog(rootPane,"Nilai Harus 0-100");
    }
    else if ((input >100)){
        JOptionPane.showMessageDialog(rootPane,"Jumlah Nilai Melebihi Batas");
    }
       // TODO add your handling code here:
    }//GEN-LAST:event_tutsKeyReleased

    private void tuasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tuasKeyReleased
    int input = Integer.valueOf(tuas.getText().trim());
    if ((input < 0)){
        JOptionPane.showMessageDialog(rootPane,"Nilai Harus 0-100");
    }
    else if ((input >100)){
        JOptionPane.showMessageDialog(rootPane,"Jumlah Nilai Melebihi Batas");
    }       // TODO add your handling code here:
    }//GEN-LAST:event_tuasKeyReleased

    private void ttugasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ttugasKeyReleased
    int input = Integer.valueOf(ttugas.getText().trim());
    if ((input < 0)){
        JOptionPane.showMessageDialog(rootPane,"Nilai Harus 0-100");
    }
    else if ((input >100)){
        JOptionPane.showMessageDialog(rootPane,"Jumlah Nilai Melebihi Batas");
    }       // TODO add your handling code here:
    }//GEN-LAST:event_ttugasKeyReleased

    private void thadirKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_thadirKeyReleased
    int input = Integer.valueOf(thadir.getText().trim());
    if ((input < 0)){
        JOptionPane.showMessageDialog(rootPane,"Jumlah Kehadiran 0-16");
    }
    else if ((input >16)){
        JOptionPane.showMessageDialog(rootPane,"Jumlah Kehadiran Melebihi Batas");
    }        // TODO add your handling code here:
    }//GEN-LAST:event_thadirKeyReleased

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /*
//         * Set the Nimbus look and feel
//         */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /*
//         * If Nimbus (introduced in Java SE 6) is not available, stay with the
//         * default look and feel. For details see
//         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /*
//         * Create and display the form
//         */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new FormMhs("").setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bhitung;
    private javax.swing.JButton bkeluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jkembali;
    private javax.swing.JTextField takhir;
    private javax.swing.JTextField tgrade;
    private javax.swing.JTextField thadir;
    private javax.swing.JTextField tnama1;
    private javax.swing.JTextField tnim1;
    private javax.swing.JTextField ttugas;
    private javax.swing.JTextField tuas;
    private javax.swing.JTextField tuts;
    // End of variables declaration//GEN-END:variables
}
